version: "3.9"

services:
  api:
    container_name: node-api
    build:
      context: .
      dockerfile: Dockerfile
      target: base        # production stage
    image: node-api:latest
    ports:
      - "4000:4000"
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    profiles: ["prod"]

  api-debug:
    container_name: node-api-debug
    build:
      context: .
      dockerfile: Dockerfile
      target: debug       # debug stage
    image: node-api-debug:latest
    ports:
      - "4001:4000"
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src   # live code editing
    stdin_open: true
    tty: true
    restart: unless-stopped
    profiles: ["debug"]
