apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
        - name: node-api
          image: <acr-name>.azurecr.io/node-api:latest
          ports:
            - containerPort: 4000
          envFrom:
            - secretRef:
                name: node-api-secrets
          readinessProbe:
            httpGet:
              path: /api/health
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: node-api-svc
spec:
  type: ClusterIP
  selector:
    app: node-api
  ports:
    - port: 4000
      targetPort: 4000
